import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/components/globals.css";
import AuthProvider from "@/providers/AuthProvider";
import MoviesProvider from "@/providers/MoviesProvider";
import Footer from "@/components/footer/Footer";
import HeaderBar from "@/components/headerBar/HeaderBar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthProvider>
          <MoviesProvider>
            <div className="app-container">
              <HeaderBar />
              <main className="main-container">{children}</main>
              <Footer />
            </div>
          </MoviesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
